### ISSUE TITLE
골드바흐의 추측(6588)_deious

### ISSUE THREAD

**Issue by deious** [as-is-as/Basic#10]
int main()
	{
		bool num[1000000] = { false, };

		num[0] = true;
		num[1] = true;

		for (int i = 2; i <= 1000000; i++) {
			if (!num[i]) {
				for (int j = i * 2; j <= 1000000; j += i) {
					num[j] = true;
				}
			}
		}
		// 1. 입력 값을 받음 2. 입력 값을 두개의 소수로 분해함 3. 두개의 소수값의 합이 입력값과 같은지 확인

		return 0;
	}

골드바흐의 추측 문제에서 입력받은 짝수를 두 개의 소수 합으로 표현할지 모르겠습니다.

**Comment by SungBeom** [comment]
에라토스테네스의 체 알고리즘을 이용하여 소수 판별 배열을 작성한 것까지는 잘하셨습니다.
이후에 입력 받은 짝수(편의상 even이라 하겠습니다.)에 대해, 해당 수보다 작은 소수(primary)들을 순회하며 even - primary가 소수인지 확인해보면 됩니다 :)

**Comment by deious** [comment]
감사합니다. 큰 도움이 되었습니다.
