### ISSUE TITLE
연산자 끼워넣기(14888)_2_deious

### ISSUE THREAD

**Issue by deious** [as-is-as/Basic#25]
```
#include <iostream>
#include <vector>
using namespace std;

int num;
int max = -1000000000, min = 1000000000;
vector<int> v(11);

void caculate(int index, int plus, int minus, int mul, int div, int sum)	// 계산 하는 식이 필요한 상황 어떻게 구현을 해야 하는가?
{
	if (index > num -1)
	{
		return;
	}

	if (plus < 0 || minus < 0 || mul < 0 || div < 0)
	{
		return;
	}

	if (sum > max) {
		max = sum;
	}

	if (sum < min)
	{
		min = sum;
	}

	caculate(index+1, plus - 1, minus, mul, div ,v[index] + v[index+1]);
	caculate(index+1, plus, minus - 1, mul, div, v[index] - v[index+1]);
	caculate(index+1, plus, minus, mul - 1, div, v[index] * v[index + 1]);
	caculate(index+1, plus, minus, mul, div - 1, v[index] / v[index + 1]);
}

int main()
{
	cin >> num;

	for (int i = 0; i < num; i++)
	{
		int a;
		cin >> a;
		v[i] = a;
	}

	int plus, minus, mul, div;
	cin >> plus >> minus >> mul >> div;
	caculate(0, plus, minus, mul, div, 0);
	cout << max << '\n' << min;
	return 0;
}
```

연산에 대한 식을 적용하는 것이 필요한데 어떻게 구현을 해야 할지 모르겠습니다.

**Comment by SungBeom** [comment]
연산에 대한 식을 적용하는 것이 정확히 무슨 말인지 모르겠지만, 답이 나오지 않는다는 가정하에 최대한 도움이 될만한 코멘트를 달아드리겠습니다.
먼저 문제 풀이를 재귀의 방식으로 접근한 것으로 보입니다. 핵심이 되는 calculate 함수에 넘겨지는 인자들이 많은데 index는 vector에서 어디를 보고 있는지, plus, minus, mul, div는 각각 더하기, 빼기, 곱하기, 나누기의 연산자의 수가 얼마나 남았는지, sum은 현재까지 계산된 결과로 해석되네요.

결국 중요한 것은 종료 조건과 흐름 처리가 되는데, 먼저 종료 조건은 index가 (num - 1)보다 커진 시점이 맞습니다. num개의 숫자 이후로 계산할 수는 없을테니까요.
다음은 흐름 처리인데 현재 코드에서는 더하기, 빼기, 곱하기, 나누기 중 그 어떤 연산자라도 없으면 반환을 하게 됩니다. 여기에는 논리적 모순이 있는데요. 반례로 충분히 많은 연산자 중 하나의 연산자가 없는 경우에 그 어떤 연산도 하지 않게 됩니다. 해당 문제를 해결하기 위해서는 더하기 연산을 하게 되는 경우인 caculate(index+1, plus - 1, minus, mul, div ,v[index] + v[index+1]); 행에서 plus의 수가 0보다 클 때 진행할 수 있도록 변경하는 것이 모순이 없어 보이네요 :)
